# Generated by Django 3.1.4 on 2021-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small',
            field=models.BooleanField(default=False),
        ),
    ]
