# Generated by Django 3.1.4 on 2021-03-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210324_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
