# Generated by Django 3.1.4 on 2021-04-01 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='productName',
        ),
        migrations.AddField(
            model_name='comment',
            name='customerName',
            field=models.CharField(default='Anonymous ', max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='comment',
            name='productID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=200),
        ),
    ]
