# Generated by Django 3.1.4 on 2021-05-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='productName',
        ),
        migrations.AlterField(
            model_name='rate',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
