# Generated by Django 3.1.4 on 2021-06-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210603_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stroke',
            field=models.IntegerField(default=0),
        ),
    ]
